### ISSUE TITLE
How to use multi CPU work for compression?

### ISSUE THREAD

**Issue by bqf9979** [ulikunitz/xz#38] opened 2020-12-02 06:01 UTC
The new version of XZ utils supports multi CPU simultaneous compression, which will greatly improve the efficiency. How to implement it,thanks!

**Comment by ulikunitz** [comment] 2020-12-02 07:11
Sorry, the library doesn't support multiple CPUs right now.

**Comment by bqf9979** [comment] 2020-12-02 07:31
ohh



---Original---

**Comment by ulikunitz** [comment] 2021-02-21 10:48
This is a duplicate of #18 and I close it therefore.

**Closed by ulikunitz** 2021-02-21 10:48 UTC
